### ISSUE TITLE
[FEATURE] Add NEAR Wallet Selector 

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#29]
# User Story(s):
As a user i want to interact with near blcokahin
# Description
Integrate NEAR Wallet selector
# Acceptance Criteria
- add all relevant wallets, Nightly, HERE Wallet, Mintbase Wallet, NEAR Snap, Coin98, Welldone, Mobile Wallet, Meteor, MyNEARWallet
# Resources
- https://github.com/near/wallet-selector/

**Comment by lachlanglen** [comment]
@codingshot closing as I believe this is done, if there are follow-on issues let's create new ticket
