### ISSUE TITLE
[FEATURE] Profile Dropdown & Logout on Navbar

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#30]
# Problem
When logged in, it clicks to logout when normally this would be where. a drop down would happen. N
# User Story(s):
 As a user, I want to have a drop down to logout, so that I don't accidentally logout

# Description
Profile drop down

# Acceptance Criteria
- show preview image like in near.social of that users nearsocial profile image, if thye dont have one then use default potlock image
- drop down should show logout and also my profile. My profile shoudl route to potlock profile page where it passes profile id in props so this can be easily shared (iike in near social)
# Limitations 
- need to pull from near social for profile information
- still waiting for designs for this https://trello.com/c/Wt9EzBF6
# Resources
- outline links and relevant resources, references implementations

**Comment by lachlanglen** [comment]
Completed
