### ISSUE TITLE
[BUG] Amount Raised on Project Cart Not Displaying Correctly

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#31]
**Describe the bug**
Currently showing hardcoded value of $24.000 needs to pull each project
<img width="1373" alt="Screenshot 2024-01-17 at 2 40 30 AM" src="https://github.com/PotLock/next-app/assets/45281667/a0f7e325-778c-474f-b912-21c715f61406">
 on donations contract and show USD value (NEAR value if API isn't owrking
**To Reproduce**
1. Go to 'alpha.potlock.org
2. Scroll to any page

**Expected behavior**
Should show current amount raised through each project

Resources
- Coingecko APi, RefApi for prices

**Comment by lachlanglen** [comment]
This appears to be complete
