### ISSUE TITLE
[ENHANCE] Finish Project Page Header

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#32]
# Title
Project page header needs to be finished
# Acceptance Criteria
- need to add correct tabs with active link
- add profile iamge and banner or use default potlock images
- add share link that shares link to proejct and alsos passed referredId of logged in name if used logged in so we can use for fees
<img width="1427" alt="" src="https://github.com/PotLock/next-app/assets/45281667/73ed89c0-b01b-4e92-997b-098d02d1c931">

**Comment by lachlanglen** [comment]
@phuongfunny is this deployed yet?

**Comment by lachlanglen** [comment]
I see the header images but no link.

> add share link that shares link to proejct and alsos passed referredId of logged in name if used logged in so we can use for fees

actual:

![Image](https://github.com/PotLock/next-app/assets/54282009/d3dd27ae-6ae2-40e6-a9f6-23b545d8fbed)

design:



![Image](https://github.com/PotLock/next-app/assets/54282009/77089856-eebb-40e6-ab1c-1aa87061cf64)

**Comment by phuongfunny** [comment]
@lachlanglen let me check and fix it. Thanks

**Comment by phuongfunny** [comment]
@lachlanglen Hi, i was fixed this issue. Please help me check. Thanks

**Comment by phuongfunny** [comment]
Hi @lachlanglen , i was fixed this issue, please help me check. Thanks

**Comment by lachlanglen** [comment]
Thanks
