### ISSUE TITLE
[ENHANCE] Overview on Project Page Should Have Markdown Support

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#33]
# Summary
- Overview on proejct showing hashtags and markdown styling as it is supported across near social profiles. We should add markdown support on near social profiles

# Acceptance Criteria
- after pulling profile image add markdown parser
- 
![2024-01-17 02 47 03](https://github.com/PotLock/next-app/assets/45281667/c0b59acd-3739-4f1b-aca8-d61abdd1ceba)

**Comment by lachlanglen** [comment]
Completed
