### ISSUE TITLE
[FEATURE] Project Page Should Display Team Members

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#34]
# Problem
Project page currently does not display team memb ers
# User Story(s):
 As a team member, I want to have my profile show on profile page, so that others can follow and find me

# Description
Description of solution

# Acceptance Criteria
- show preview of image with name form near social
- hover affect like in near social where can navigate to potlock porfile and also follow directly from their

# Limitations 
- need to pull from social.near to pull this information that may be through an ipfs gateway
# Resources
- Team Examples from BOS https://github.com/PotLock/bos-app/blob/main/apps/potlock/widget/Project/Team.jsx
<img width="1429" alt="" src="https://github.com/PotLock/next-app/assets/45281667/e1949a06-db38-489b-8ffa-966e592cb00d">
<img width="1169" alt="" src="https://github.com/PotLock/next-app/assets/45281667/a24245d6-64d6-459c-b9da-15c7e8ff923d">

**Comment by lachlanglen** [comment]
Closing; no hover effect yet but will create separate ticket for that.
