### ISSUE TITLE
[BUG] Showing Unapproved Projects on Explore Page

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#35]
**Describe the bug**
Pulling all names from project registry but should only pull approved projects. Only the admins should show all projects (can pull admin from registry.potlock.near) 
**To Reproduce**
1. Go to home page

**Expected behavior**
For not logged in users and all loggedin users but admins it should only show projects that are approved onr egistry
**Screenshots**
Example efiz.near and gojo academy are unapproved projects
![Image](https://github.com/PotLock/next-app/assets/45281667/667f29fe-fb54-4e1a-bd3d-fe69b9d6dbf5)

**Comment by lachlanglen** [comment]
This appears to be fixed
