### ISSUE TITLE
[FEATURE] Pull Pots from Pot Testing Contract

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#36]
# Problem
Currently only showing layout need to integrated (pot) quadratic funding contracts from o chain
# User Story(s):
 As a user, I want to be able to view pots from on chain, so that I can go to the pot page

# Description
On chain gallery of pots
# Acceptance Criteria
- view pots
- filter by stage in pot
- show accurately how much time is left
- click on pot and see how much is left
- see how many contirbutors
- see how much is in contract in NEAR but use coingecko (or whatever price api) to display in USD -> fall back to near
# Limitations 
- need to swich to mainnet pot and make it easy to switch once complete
# Resources
- https://potlock.org/figma
![Explore pots](https://github.com/PotLock/next-app/assets/45281667/d3f27270-e814-4147-969a-f0c2c3fa75b8)

**Comment by lachlanglen** [comment]
@vonhatcuong can you just update the "Matching Pool" sort names:

Most to Least Matching Pool
Least to Most Matching Pool

thanks, then this ticket can be complete

![Image](https://github.com/PotLock/next-app/assets/54282009/88af4762-4cdd-4eff-bb15-5b889a204622)

**Comment by vonhatcuong** [comment]
@lachlanglen please check it

**Comment by lachlanglen** [comment]
Closing this as remaining issue is being addressed in https://github.com/PotLock/next-app/issues/54
