### ISSUE TITLE
[FEATURE] Explore Projects, Search, Filter

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#37]
# Problem
Need to be able to search and filter through approved projects on registry
# User Story(s):
 As a user , I want to be able to find projects by least donations or by categories, so that I can find projects I want to donate too

# Description
Explore page
# Acceptance Criteria

- [x] - filter by least and most donations
- [x] - filter by most and recent donations
- [x] - show project cards with donate and add to cart
- [x] - make sure amount raised is enough #31 
- [x] - use default fall back iamge
- [x] - show stats of proejcts correctly
- [x] - accurately show project count based on filter
- [x] - have featured projects with sliders
- [x]  load more on bottom of card
- [x] show stats propoerly

# Limitations 
- indexers on registry are slow
- rember to put approved projects #35 
# Resources
- https://potlock.org/figma
![Home (5)](https://github.com/PotLock/next-app/assets/45281667/32e21c23-31f8-485f-9353-c28021b897a9)

**Comment by lachlanglen** [comment]
@vonhatcuong When I choose any filter, only 9 results are returned

![Image](https://github.com/PotLock/next-app/assets/54282009/5d6a0250-b259-400b-a409-9618a5488dd1)

**Comment by lachlanglen** [comment]
Looks better now, thanks @vonhatcuong
