### ISSUE TITLE
[FEATURE] Donate Popup

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#38]
# Problem
Friction of going and adding to cart then putting in price is screwing up flow of donations. 
# User Story(s):
As a user I want to select how much and what currency I want to donate to.

# Description
Donate popup accessible from project page and project card that allows you to enter amount and currency and donate directly with success screen
# Acceptance Criteria
- [x] Donate popup
- [x] Accessible from donate button on project card
- [x] Accesible from doante page on project profile
- [x] Drop down fungible toknes
- [x] Show price equivalent and amount
- [x] Allow to add to cart (saves in local storage)
- [x] Button to donate directly
- [x] Show break down of fees with dropdown
- [ ] Add optional fees (not sure if this in design
- [x] Show success screen if donated usccess 
- [x] succes screen shows share to social button
- [x] success screen show donor name with near social profile
- [x] success screen shows amount in NEAR
- [x] susccess screen shows transactino has and opens in new tab on nearblocks
- [x] minimum amount on front end to cover storage costs. 
- [x] donate.potlock.near to initatie 
- [x] add referral fees if ferrer sent link (maybe through local storage or throuhg app props)
- [x] ability to add note (pass into donate.potlock.near)
# Limitations 
- need external api for token price

# Resources
![SIngle entry Donation](https://github.com/PotLock/next-app/assets/45281667/291fab1e-003d-471b-957f-f2a6a65de235)

**Comment by vonhatcuong** [comment]
@lachlanglen  Add optional fees (not sure if this in design) -> no has design and I think it's not necessary with this mvp

**Comment by lachlanglen** [comment]
Will create a separate ticket for optional fees
