### ISSUE TITLE
[FEATURE] Featured Projects

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#39]
# User Story(s):
 As a project, I want to my project to be highlighted, so that I can get more donations
As a user, I want to donate to filtered projected, so that i know they are vetted.

# Description
Project slider of project cards that can be whitelisted from array of accountids.
# Acceptance Criteria

- [x] display project cards
- [x] pull from whitelist in app of project accountid
- [x] slider that revolves arounds
Bonus
- [x] Dont show project if it gets flagged (unlikely to happens as admin needs to add this

# Resources
<img width="771" alt="" src="https://github.com/PotLock/next-app/assets/45281667/e7350583-2104-4106-a4ef-9eabef7d4ffa">

**Comment by lachlanglen** [comment]
@phuongfunny slider doesn't revolve around. I should be able to keep clicking the left or right arrow and it should continue rotating, rather than stopping at the end. See screen video below



https://github.com/PotLock/next-app/assets/54282009/5ece492d-40b3-4de4-8871-1f64cc898f1e

**Comment by phuongfunny** [comment]
@lachlanglen  Hi, i was fixed this issue. Please help me check. Thanks

**Comment by lachlanglen** [comment]
Fixed thanks
