### ISSUE TITLE
[FEATURE] Create Cart Layouts

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#40]
# User Story(s):
As a donor, I want the ability to add to a cart even if im not logged in, so that i can easily shop later
As a donor, I want to edit amounts, delete things from cart, see breakdowns, and set optional fees, so I can donate exactly what I want. 

# Description
A cart front end that allows you to add items from across the app to local storage saved in cart, and then donate all. Can also support pots.
# Acceptance Criteria

- [ ] label direct donations
- [ ] select and deselect items in cart
- [ ] show break down and has referral fees (with referrer? <- i dont think has design
- [ ] all projects should display information from social account
- [ ] click on project name and it should go to project page
- [ ] ability to drop down different supported fungible tokens
- [ ] shows USD preview of currency amount with whatever is used for token price API
- [ ] able to select all and delete from cart
- [ ] show total amount with breakdown
- [ ] separate pots
- [ ] show quadratic funding rounds
- [ ] show error if not qualified to donate for pot (with popup for qualifications)
- [ ] show if users don't have enough balance and tell them how much balance they have
- [ ] make sure cannot add to cart twice can only change amounts

# Limitations 
- need to still pull from API and have items added to cart
- need to use near social api and price oracle to determine prices of token in USD and also display profile image
# Resources
![Home (6)](https://github.com/PotLock/next-app/assets/45281667/3fd92e8b-f907-412e-b4e6-5ef5453bae09)

**Comment by lachlanglen** [comment]
Closing this; large amount completed and individual remaining items can be addressed in separate tickets.
