### ISSUE TITLE
[FEATURE] Favicon, description, meta preview image, site tiltle for each page. 

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#42]
# Problem
Currently show nextjs app

# Description
Updated favicon, description, and site title
# Acceptance Criteria

- [x] favicon
- [x] metadescription image
- [x] site title
- [x] site description

# Resources

Name
Potlock
Description
Potlock, is bringing new funding mechanisms to the table for public goods, built on NEAR Protocol
Image
![PotLockMedia](https://github.com/PotLock/next-app/assets/45281667/ff9319a9-2665-471b-8b67-2f14ba9d7d21)

Favicon
![PotlockAvatarTan (1)](https://github.com/PotLock/next-app/assets/45281667/0474d6db-9683-4e5d-b542-3c6a03be2baa)

**Comment by vonhatcuong** [comment]
site title
site description
Could you please provide an example, @codingshot?

**Comment by vonhatcuong** [comment]
@lachlanglen 
site title
site description
Could you please provide an example?

**Comment by phuongfunny** [comment]
@lachlanglen  i was fixed this issue, pls help me check. thanks

**Comment by lachlanglen** [comment]
I think this looks good, will wait for @codingshot to approve

**Comment by lachlanglen** [comment]
actually we can close this
