### ISSUE TITLE
[FEATURE] Pot Card

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#53]
# Problem
Need a pot card to be used on #52 and from pot explore
# User Story(s):
 As a developer, I want to have a pot component I can reused for differnet profiles, so that I can speed up developers

# Description
Pot card
# Acceptance Criteria

- [x] display pot description
- [x] clip text
- [x] display pot status
- [ ] pass in pot contract address to component 
- [x] use price api to show maount matched
- [x] Show name and description
- [x] add near api js connection
-

- maybe helper function for determining

# Resources
Pot implementation on BOS
https://github.com/PotLock/bos-app/blob/main/apps/potlock/widget/Pots/Card.jsx
![Pots (1)](https://github.com/PotLock/next-app/assets/45281667/6c60e295-41ae-4ab2-bfbd-b953c0ad4ca7)

**Comment by vonhatcuong** [comment]
@codingshot  pass in pot contract address to component 
What does this mean?

**Comment by lachlanglen** [comment]
@vonhatcuong  I'm not sure what he means or why that is needed. Is this complete otherwise?

**Comment by vonhatcuong** [comment]
@lachlanglen Please help me test the finished features

**Comment by lachlanglen** [comment]
@vonhatcuong pot card doesn't currently display status as per requirements

![Image](https://github.com/PotLock/next-app/assets/54282009/68ff4fbe-37d2-4ce4-9c47-80d257c9257c)

**Comment by vonhatcuong** [comment]
@lachlanglen 

![Image](https://github.com/PotLock/next-app/assets/66981545/bf462689-35c4-432e-8f3f-fec372b968b9)

 Do you mean 1 day left for Matching ? Currently, these pots have been applied so it will not be displayed. Please check the logic again

**Comment by lachlanglen** [comment]
Ok I see, I think the designs need updating. Will mark this as closed.
