### ISSUE TITLE
[FEATURE] Explore Pots Layout + API

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#54]
# User Story(s):
As a donor, I want to see pots, so that I can can navigate to quadratic funding round

# Description
Description of solution

# Acceptance Criteria

- [x] deploy pot if on admin whitelist (admin whitelist will be based on the front end)
- [x] only display pots on front end from whitelist
- [x] show featured pots
- [x] featued pots will be on whitelist
- [x] if no featured pots do not show section
- [x] llink to tool pic about pot with description
- [x] pull from pots from factory contract
- [x] keep pot deployer v1.pot.potlock.ner as variable
- [x] add filters based on stages
- [x] show active pots frist
- [x] add sort based on most donations and most contirubuots
- [x] use #53 
- [x] click on pot and goes to pot page
- [x] add banner 
- [x] add price raised
- [x] show number of pots in search
- [x] search pot by name 

# Limitations 
- will be harder to index all deployed pots (available on pot page) as referance
- need to account for price across matching rounds, number of contributiorns
- 
# Resources
- References on bos.potlock.org https://github.com/PotLock/bos-app/blob/main/apps/potlock/widget/Pots/Home.jsx

![Explore pots (1)](https://github.com/PotLock/next-app/assets/45281667/4795726c-f98d-46e1-882a-532f616242f2)

**Comment by lachlanglen** [comment]
@vonhatcuong can you just update text of Matching Pool sort options:

Most to Least Matching Pool
Least to Most Matching Pool

thanks

![Image](https://github.com/PotLock/next-app/assets/54282009/f0052f22-d22e-4ca7-98c4-1f4b8766fc3e)

**Comment by vonhatcuong** [comment]
@lachlanglen please check it

**Comment by lachlanglen** [comment]
@vonhatcuong It's close - the order should be consistent though, always "Most to Least" before "Least to Most"

So:

**Most to Least Donations
Least to Most Donations
Most to Least Matching Pool
Least to Most Matching Pool
Most to Least # Donors
Least to Most # Donors**

Thanks, sorry I know it's not correct on the designs.

**Comment by vonhatcuong** [comment]
![Image](https://github.com/PotLock/next-app/assets/66981545/5046b20a-8e1e-4522-99b2-d625bbc01899)

please check it again

**Comment by lachlanglen** [comment]
Perfect, thank you
