### ISSUE TITLE
[FEATURE] Deploy Pot

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#65]
# Problem
Currently need a place outside of the NEAR CLI to deploy a pot
# User Story(s):
 As a grant organization, I want to deploy a pot, so that I can manage a quadratic funding round.

# Description
A form for deploying quadratic funding roudns with form validation. 
# Acceptance Criteria
- [x] deploy pot from factory contract
- [x] show deploy pot button from #54 page, but only to people on whitelist
- [x] set factory contract in props, also hard code and comment out for testing
- [x] form validation on date
- [x] indicate if person has enough balance to deploy
- [x] add validation for registry name and sybil settings (on advanced options) for valid near smart contract address
- [x] name and description input
- [x] info has tool tip with hover and a read more tab (don't have design for this)
- [x] sccuess screen for deploy pot = redirect to pot
- [x] validation on dates
- [x]  (application date cannot go past funding date or start after funding round has started
- [x] end dates cannot go past start dates, should show error for this
- [x] dates cannot be in past
- [x] pull from protocol fee from contract (cannot edit)
- [x]  check if chef valid address (would prefer if showed near social profile if had one
- [ ]  check max fee for pot
- [x] default nada bot contract v1.nadabot.near (no deployed yet
- [ ] add other options for config should be in form of sybil provider
- [x]  registry should only check for approved registries (for now only registry.potlock.near)
- [x] tool tips for chef fees and referrers fees
- [x] add name and description
- [ ] accurately estimate how much it costs to deploy pot
BONUS
- [x] check if wallet addresses have wasm contract deployed to it (maybe something magic build can do)

# Limitations 
- 
# Resources
- Pots deploy https://github.com/PotLock/bos-app/blob/main/apps/potlock/widget/Pots/Deploy.jsx
- Deploy Pot figma section https://www.figma.com/file/ckixqGfuRKZ63tTvdJzi6j/Potlock?type=design&node-id=6578%3A9938&mode=design&t=YFynmm31faHQYBI6-1
- #60 edit settings as reference
- Example of pot deploy https://nearblocks.io/txns/5oqFHjw6FFpD2W9X7Zdc8pqoRsDk7Ng8CFNc6ofJwWR
- Deploy Pot on BOS https://bos.potlock.org/?tab=deploypot (must be whitelisted for now)
![Deploy pot (1)](https://github.com/PotLock/next-app/assets/45281667/106ff62c-b166-4b24-8bd9-d1f5dce18ad8)

**Comment by lachlanglen** [comment]
Looks pretty good
